### ISSUE TITLE
pyqtgraph 0.13.1 should require pyqt >= 5.15

### ISSUE THREAD

**Issue by beenje** [conda-forge/pyqtgraph-feedstock#24]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Some of our pyqt apps broke when we updated `pyqtgraph` from 0.12.4 to 0.13.1 with errors like:

`AttributeError: 'QHeaderView' object has no attribute 'setResizeMode'` or `AttributeError: 'QGridLayout' object has no attribute 'setMargin'`. Those methods are deprecated but should still be available with Qt 5.12 which we are still using.

Downgrading `pyqtgraph` to 0.12.4 fixes the issue.
With version 0.13.1, I noticed a warning: `RuntimeWarning: PyQtGraph supports Qt version >= 5.15, but 5.12.9 detected.`
This comes from [pyqtgraph/Qt/__init__.py#L335](https://github.com/pyqtgraph/pyqtgraph/blob/123eca2c7d31041190c55026231c5f1d5f2aa7fb/pyqtgraph/Qt/__init__.py#L335)

The conda recipe should maybe force Qt >= 5.15 as run requirements for 0.13.1?

### Installed packages

```shell
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.3.2              h166bdaf_0    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
boost                     1.74.0           py39h5472131_5    conda-forge
boost-cpp                 1.74.0               h6cacc03_7    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
click                     8.1.3            py39hf3d152e_0    conda-forge
cpptango                  9.3.5                he78764c_1    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
executing                 1.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.9                h27087fc_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hc2a2eb6_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
gettext                   0.19.8.1          h27087fc_1009    conda-forge
glib                      2.72.1               h6239696_0    conda-forge
glib-tools                2.72.1               h6239696_0    conda-forge
gst-plugins-base          1.20.2               hcf0ee16_0    conda-forge
gstreamer                 1.20.3               hd4edc92_2    conda-forge
guidata                   1.7.9              pyh9f0ad1d_0    conda-forge
guiqwt                    3.0.7            py39hde0f152_1    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
ipython                   8.5.0              pyh41d4057_1    conda-forge
itango                    0.1.9              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang                  13.0.1          default_hc23dcda_0    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.10               h28343ad_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.72.1               h2d90d5f_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm13                 13.0.1               hf817b99_2    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libpq                     14.5                 he2d8382_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libxslt                   1.1.33               h0ef7038_3    conda-forge
libzlib                   1.2.12               h166bdaf_3    conda-forge
lxml                      4.8.0            py39hb9d737c_2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mysql-common              8.0.30               h26416b9_1    conda-forge
mysql-libs                8.0.30               hbc51c84_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numpy                     1.23.3           py39hba7629e_0    conda-forge
omniorb-libs              4.2.5                he49606f_2    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   3.0.5                h166bdaf_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py39hd5dbb17_2    conda-forge
pint                      0.19.2             pyhd8ed1ab_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pymysql                   1.0.2              pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hf3d152e_8    conda-forge
pyqt-impl                 5.12.3           py39hde8b62d_8    conda-forge
pyqt5-sip                 4.19.18          py39he80948d_8    conda-forge
pyqtchart                 5.12             py39h0fcd23e_8    conda-forge
pyqtgraph                 0.13.1             pyhd8ed1ab_0    conda-forge
pyqtwebengine             5.12.1           py39h0fcd23e_8    conda-forge
pytango                   9.3.6            py39h609f8c2_0    conda-forge
python                    3.9.13          h2660328_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pythonqwt                 0.8.3              pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h1304e3e_6    conda-forge
qtpy                      2.2.0              pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
sardana                   3.2.1post0+maxiv    pyhd8ed1ab_0    maxiv-kits
scipy                     1.9.1            py39h8ba3f38_0    conda-forge
setuptools                65.4.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snapshotlib               1.1.0              pyhd8ed1ab_0    maxiv-kits
sqlite                    3.39.3               h4ff8645_0    conda-forge
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
taurus                    5.1.4                hd8ed1ab_0    conda-forge
taurus-core               5.1.4              pyhd8ed1ab_0    conda-forge
taurus-qt                 5.1.4              pyhd8ed1ab_0    conda-forge
taurusgui-motorgui3       1.1.1              pyh1a96a4e_0    maxiv-kits
tk                        8.6.12               h27826a3_0    conda-forge
traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022d                h191b570_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zlib                      1.2.12               h166bdaf_3    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

### Environment info

```shell
active environment : pyqt
    active env location : /mxn/home/benber/.conda/envs/pyqt
            shell level : 1
       user config file : /mxn/home/benber/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (read only)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.maxiv.lu.se/get/maxiv-kits/linux-64
                          https://conda.maxiv.lu.se/get/maxiv-kits/noarch
                          https://conda.maxiv.lu.se/get/conda-forge/linux-64
                          https://conda.maxiv.lu.se/get/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /mxn/home/benber/.conda/pkgs
       envs directories : /mxn/home/benber/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.27.1 CPython/3.9.1 Linux/3.10.0-1160.36.2.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 2420:1300
             netrc file : None
           offline mode : False
```
